### ISSUE TITLE
`pynndescent` has recently changed

### ISSUE THREAD

**Issue by VallinP** [pavlin-policar/openTSNE#98]
##### Expected behaviour
Return the embedding

##### Actual behaviour
Return the embedding with one warning :
.../miniconda3/lib/python3.7/site-packages/openTSNE/nearest_neighbors.py:181: UserWarning: `pynndescent` has recently changed which distance metrics are supported, and `openTSNE.nearest_neighbors` has not been updated. Please notify the developers of this change.
  "`pynndescent` has recently changed which distance metrics are supported, "

##### Steps to reproduce the behavior
Hello World steps

**Comment by pavlin-policar** [comment]
Thank you for bringing this up. I'll look into it as soon as possible.

**Comment by mohamad-amin** [comment]
Seems like there is an error with the following line because of this recent change:
**Line:**
```python
indices, distances = self.index.query(data, k=k + 1, queue_size=1)
```
**Location:**
openTSNE/nearest_neighbors.py in build(self, data, k), line 232
**Error:**
TypeError: query() got an unexpected keyword argument 'queue_size'

**Comment by CongFang** [comment]
> Seems like there is an error with the following line because of this recent change:
> **Line:**
> 
> ```python
> indices, distances = self.index.query(data, k=k + 1, queue_size=1)
> ```
> 
> **Location:**
> openTSNE/nearest_neighbors.py in build(self, data, k), line 232
> **Error:**
> TypeError: query() got an unexpected keyword argument 'queue_size'

Hi, I also encountered this problem. Is there any solution？

**Comment by pavlin-policar** [comment]
I would suggest fixing the version of pynndescent to 0.3.3 until I can fix the code to match their latest API. So I guess running

```
pip install pynndescent==0.3.3
```

should fix things.

**Comment by CongFang** [comment]
> I would suggest fixing the version of pynndescent to 0.3.3 until I can fix the code to match their latest API. So I guess running
> 
> ```
> pip install pynndescent==0.3.3
> ```
> 
> should fix things.

It worked. Thinks!

**Comment by mohamad-amin** [comment]
I'm not sure, but I have a feeling that reverting the version of `pynndescent` increases the runtime of the code a lot. I haven't tested my hypothesis but the runtime of calculating TSNE has increased about 100X times using this package after I downgraded the version of `pynndescent`. Is there any justification for this?

**Comment by pavlin-policar** [comment]
This is entirely possible. I see that pynndescent has gotten quite an update in v0.4.*, so they might have improved the runtime of the method. One of the slowest parts of t-SNE is calculating nearest neighbors, that's why we rely on pynndescent to do it quickly. It's fantastic news if they've sped it up.

**Comment by dkobak** [comment]
A 100x times runtime increase sounds quite incredible though!

**Comment by pavlin-policar** [comment]
A 100 fold increase sounds far too good to be true tbh, but just glancing through the code, it looks like they've added a low and high memory mode, and it's set to high memory by default. So that probably has something to do with any speed-up. Even still, any improvement is very welcome.

**Comment by mohamad-amin** [comment]
Well I'm getting confused a bit! 100X increase in runtime I meant, **not** 100x speedup.
The first time that I ran the code I could run TSNE on a dataset around the shape of 10^3, 300 in about 3 seconds, the next times after downgrading it took more than 300 seconds.

**Comment by pavlin-policar** [comment]
Well, that is bizarre indeed. 1000x300 should certainly not take 300 seconds to run in any setting, using any approximation. I would guess that something else is going on here. If you can replicate this, please send me the information with your python environment and a code snippet so we can try to work this out.

**Comment by pavlin-policar** [comment]
I've released v0.3.12 on PyPi, which fixes this problem, so you can install a patched version through pip. Conda-forge takes a little bit of time to realise there's a new version, but it should be up there in a couple of hours as well.

**Comment by dkobak** [comment]
FWIW it's still 0.3.11 on conda-forge...

**Comment by pavlin-policar** [comment]
Yeah, for some reason, the conda-forge bot took a long time to detect the new version on PyPi. But it's updated now.

**Comment by VallinP** [comment]
Thank you.

**Comment by Yuran-Zhao** [comment]
Hi, I still encounter this UserWarning after I installed the v0.3.12. 
And I cannot get the embeddings after a long time when running :
`x = iris["data"]`
`embeddings=tsne.train(x)`
Is that normal?

**Comment by pavlin-policar** [comment]
The warning indicates a mismatch between the metrics that pynndescent and opentsne, and this can occur when pynndescent updates the distances it supports. That said, please make sure you have the latest version of pynndescent -- from what I can tell, this warning shouldn't be showing with the latest versions of both packages.

**Comment by Yuran-Zhao** [comment]
> The warning indicates a mismatch between the metrics that pynndescent and opentsne, and this can occur when pynndescent updates the distances it supports. That said, please make sure you have the latest version of pynndescent -- from what I can tell, this warning shouldn't be showing with the latest versions of both packages.

Thanks! The UserWarning does disappear after I upgrading the pynndescent from 0.4.3 to 0.4.5. And it works well now.
